[bindings]
a = "KeyA"
b = "KeyS"
select = "KeyQ"
start = "KeyW"
up = "ArrowUp"
down = "ArrowDown"
left = "ArrowLeft"
right = "ArrowRight"
pause = "KeyP"
exit = "Escape"
log_ops = "KeyL"
dump_memory = "Comma"