[package]
name = "deemgee-opcode"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling = "0.13.1"
proc-macro2 = "1.0.33"
quote = "1.0.10"
syn = "1.0.82"
